### ISSUE TITLE
Question or fix

### ISSUE THREAD

**Issue by abelykh0** [floooh/chips#12]
Line 863 of z80.template.h

```cpp
if (nmi || (((pins & (Z80_INT|Z80_BUSREQ))==Z80_INT) && (r2 & _BIT_IFF1))) {
```
Can we just change to:

```cpp
if (nmi || (((pins & Z80_INT)==Z80_INT) && (r2 & _BIT_IFF1))) {
```

or it was some idea that was not implemented yet?

**Comment by floooh** [comment]
Yeah, the Z80_BUSREQ can be removed since that pin isn't emulated anyway. I'll do the fix.
