### ISSUE TITLE
c64 system assert

### ISSUE THREAD

**Issue by nurpax** [floooh/chips#16]
If I initialize a pixelbuffer for a c64 system with the following code:

```
    const size_t framebuf_size = 392*272*4;
    uint8_t* framebuf = malloc(framebuf_size);
    desc.pixel_buffer = framebuf;
    desc.pixel_buffer_size = framebuf_size;

    // Initialize C64 system
    c64_t sys;
    c64_init(&sys, &desc);
```

I get this assertion:

```
janne@janne-X10SRA:~/dev/c64emu$ gcc c64.c -o c64 && ./c64
hello world
c64: chips/systems/c64.h:247: c64_init: Assertion `!desc->pixel_buffer || (desc->pixel_buffer_size >= ((((62)+1)*8)*((311)+1)*4))' failed.
Aborted (core dumped)
```

But a quick reading of the systems/c64.h docs would suggest this pixel_buffer_size would be ok:

```
    /* video output config (if you don't want video decoding, set these to 0) */
    void* pixel_buffer;         /* pointer to a linear RGBA8 pixel buffer, at least 392*272*4 bytes */
    int pixel_buffer_size;      /* size of the pixel buffer in bytes */
```

**Comment by floooh** [comment]
Oops, sorry about that, the comment isn't correct, and I updated that.

The "recommended" way to query the required display buffer size in number of bytes is by calling ```c64_max_display_size()```, this can be called before c64_init() and returns a "safe" constant.

The max pixel buffer size is bigger than expected for the VIC-II debug visualization which renders the entire PAL frame (also the parts that are outside the screen).
