### ISSUE TITLE
test programs

### ISSUE THREAD

**Issue by mrdudz** [floooh/chips#17]
not really an issue, but since you mentioned the lorenz testsuite ... we have collected a whole lot of test programs for VICE here: https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/ (i have fixed a bunch of things in the lorenz suite for that matter, all tests pass on a real C64, and using both types of CIAs -> https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/general/Lorenz-2.15/ )

there is also a testbench script that can run a lot of them automatically and produce a result like here: https://vice-emu.pokefinder.org/index.php/Testbench

have fun!

**Comment by floooh** [comment]
Thanks a lot for the heads up :) I actually stumbled over the VICE tests a couple weeks ago and started to use them for testing, although nothing automated so far :)

The fixes to the Lorenz test suite are very welcome. Thanks!
