### ISSUE TITLE
z80 debugger traps cause incorrect HL<=> IX/IY renaming on next instruction

### ISSUE THREAD

**Issue by carlc27843** [floooh/chips#30]
For example:
0000:   DD 21 EF BE       LD IX,BEEF
0004:   2A AD DE           LD HL,(DEAD)

Put a breakpoint on 0004 in the debugger, then single step. IX gets the value of (DEAD) instead of HL.

In z80_exec the "call track evaluation callback if set" block may get a non-zero trap_id from the trap callback and then break out of the loop, thereby skipping the following logic in the "clear state bits for next instruction" block. This causes 'map_bits' to persist the _BITS_USE_IXIY flags to the next instruction, which if you're unlucky might reference HL.

I wasn't confident the entire "clear state bits for next instruction" block should happen before the trap since the 'pins' are passed into the trap but modified by that block.

**Comment by floooh** [comment]
Yep definitely looks like a bug, good catch!

I think the trap call should happen right the closing brace of the tick loop, except that the INT bit must not be deleted from pins before the trap call (this after the call, but both in the break and continue case).

I'll try to fix this tomorrow or over the weekend.

**Comment by floooh** [comment]
Ok, this should be fixed in the commit associated with this ticket, I've ran the Z80 tests and also validated the before/after behavior with your small test program.

The web page at https://floooh.github.io/tiny8bit/ hasn't been updated yet, doing that now.

**Comment by carlc27843** [comment]
Awesome, thanks!
