### ISSUE TITLE
Imgui 1.79 breaks debugger

### ISSUE THREAD

**Issue by tomgwozdz** [floooh/chips#43]
Imgui 1.79 changes how the clipper API works.  This breaks the disassembly and execution history views in the ui_dbg.h module.

> ImGuiListClipper: Renamed constructor parameters which created an ambiguous alternative to using the ImGuiListClipper::Begin() function, with misleading edge cases. Always use ImGuiListClipper::Begin()! Kept inline redirection function (will obsolete). Note: imgui_memory_editor in version 0.40 from imgui_club used this old clipper API. Update your copy if needed.

**Comment by floooh** [comment]
Thanks for the heads up, I haven't upgraded to ImGui 1.79 yet, the sokol-samples are even still on 1.77. I'll have to fix quite a few other places too. Will try to do this soon-ish.

**Comment by floooh** [comment]
FYI I'm seeing a small issue in cimgui when updating to 1.79 (see https://github.com/cimgui/cimgui/issues/166). I'll wait with the update until I know whether this is a bug or a feature ;)

**Comment by floooh** [comment]
Ok this should be fixed now in https://github.com/floooh/chips/commit/d5ae524e6eb02b0dc63d29e7d6740a02119d5ccc, not 100% sure, but I think those fixes also work in earlier ImGui versions, so code that isn't on 1.79 yet should also continue to work.
