### ISSUE TITLE
Question about memory allocation

### ISSUE THREAD

**Issue by aganm** [floooh/chips#45]
I read your article 'One year of C' where you mentioned that the entire 8-bit emulator didn't have a single call to malloc.

How can I avoid malloc if I need a variable size structure like a c++ vector? Everytime I need a struct that can contain a variable number of elements, I use this pattern:
```
struct many {
    int *values; // pointer to malloced buffer
    int max_values;
    int n_values;
};

```
I feel like I missed something.

**Comment by floooh** [comment]
I basically use a "three-step-approach":

1. if the max number of items is know at "compile time" and there isn't too much waste I embed the array directly:

```c
#define MAX_VALUES (128)
struct many {
    int values[MAX_VALUES];
    int num_values;
};
```

2. If the max number of items is known upfront at runtime by the library user, I allocate once during initialization (but don't allow growing the array).

```c
struct many {
    int* values;
    int max_values;
    int num_values;
};
```

3. Worst case is creating a std::vector like growable array with re-allocation.

Usually I prefer (1) or (2) and try to avoid (3).

**Comment by floooh** [comment]
Oh and PS: specifically in the emulators there are no 'dynamic-size-arrays', because the emulated hardware is "fixed" too. E.g. a C64 always has 8 sprite units, a Z80 CTC always has 3 counter channels, and so on.
