### ISSUE TITLE
Reminder: potential bug in m6502 for NMI detection

### ISSUE THREAD

**Issue by floooh** [floooh/chips#52]
Apparently there's a bug in the 6502's NMI detection (via Mathias Bergvall):

> However, while looking at this I did find a scenario where NMI is totally ignored by the m6502 simulator. That is when NMI is asserted before the third step of an branch instruction (case (op<<3)|2).
nmi_pip is set to 1 at the start of tick() which is then right-shifted (because of "taken branch delays interrupt handling by one instruction" handling I presume) and not shifted back in at the end.

**Comment by mathias110** [comment]
Hi,

I have attached two patches to the chips-test and the chips repositories.
The two new test runs a small program with branches and asserts nmi/irq at different cycles. The interrupts can either be pulsed for a single cycle or stay asserted.With the chips-patch either configuration passes, without it the NMI test fails.

/Mathias

[chips_test_nmi.patch.txt](https://github.com/floooh/chips/files/5952959/chips_test_nmi.patch.txt)
[chips_nmi.patch.txt](https://github.com/floooh/chips/files/5952965/chips_nmi.patch.txt)

**Comment by floooh** [comment]
Oki, better late then never, I have added the test from @mathias110, but used the fix from @Moosfet, it's currently in the branch z80-ticked, but this will soon-ish be merged back into master.

Many thanks!
