### ISSUE TITLE
Z80 Chip doesn't handle LD A,(IX+n) correctly

### ISSUE THREAD

**Issue by OfficialPixelBrush** [floooh/chips#58]
For example:
```x86asm
writeHelloWorld:
; IX used as pointer
LD IX,0
; hello offset + pointer
LD A,(IX+hello)
; output on data bus to LCD
OUT (1),A
; increment IX
INC IX
JP NZ,writeHelloWorld 
HALT

hello:
    DEFM  "Hello, world!",0```

Should result in the Chip outputting the ASCII Characters for "Hello, World!" onto the Databus. 
Instead, only H is printed, then the program ends.

**Comment by floooh** [comment]
As far as I can see, none of the instructions in this program set any flags, so the ```JP NZ``` would either never or always loop, depending on the intial state of the Z flag before the program was started.

**Comment by floooh** [comment]
PS: this modified program should work as expected (compare A against 0 before the JP NZ, and the writeHelloWorld had to be moved after the ```LD IX,0```, otherwise it would undo the ```INC IX```:

```
	; IX used as pointer
	LD IX,0
writeHelloWorld:
	; hello offset + pointer
	LD A,(IX+hello)
	; output on data bus to LCD
	OUT (1),A
	; increment IX
	INC IX
	CP 0
	JP NZ,writeHelloWorld 
	HALT
hello:
    	DEFB "Hello, world!",0
```

**Comment by OfficialPixelBrush** [comment]
Now I do feel quite silly. Apologies for that.
Thanks for the help though!

**Comment by floooh** [comment]
No problem :)
