### ISSUE TITLE
Z80 wait state handling incorrect?

### ISSUE THREAD

**Issue by tsarna** [floooh/chips#64]
I was looking at the Z80 emulator (very nice!) and I think the wait state handling is incorrect, except for in opcode fetch. A memory system or IO peripheral is supposed to be able to assert wait states that are relevant to it, based on decoding address and control lines, but that wouldn't be possible in the emulator currently. Consider for example:

```
        // ED 70: IN (C) (M:2 T:8)
        // -- ioread
        case 1196: goto step_next;
        case 1197: goto step_next;
        case 1198: _wait();_ioread(cpu->bc);goto step_next;
        case 1199: cpu->dlatch=_gd();cpu->wz=cpu->bc+1;goto step_next;
        // -- overlapped
        case 1200: _z80_in(cpu,cpu->dlatch);goto fetch_next;
```

/WAIT is checked simultaneously with asserting the address and relevant control pins, so a peripheral doesn't have time to assert /WAIT based on them.

Evidence:

Regarding memory access, the Z80 manual says (page 8 in the current PDF from zilog.com):

"During T2 and every subsequent automatic WAIT state (TW), the CPU samples the WAIT line with the falling edge of the clock. If the WAIT line is active at this time, another WAIT state is entered during the following cycle." However this is oversimplified. More accurately:

- For opcode fetch, figure 5 shows /M1, /MREQ, /RD and A0-A15 set up in T1, then /WAIT sampled in T2, then D0-D7 sampled at the rising edge of T3.
- For other memory reads, the behavior is slightly different, with D0-D7 sampled at the falling edge of T3 instead of the rising edge (Figure 6), but I don't think this difference matters for the emulator. Also, no M1 of course.
- Memory writes: /MREQ, D0-D7, and A0-A15 are set up in T1, then in T2 both /WR is followed by checking /WAIT (same cycle, in that order).
- IO Read and write: A0-A15 and D0-D7 (if a write) are set in T1. Then, /IORQ and either /RD or /WR are set in T2. Then, there is always at least one TW, which checks /WAIT and repeats until it's clear. Finally, T3.

(As a sanity check, I looked at the Z80180 manual as well. Fig 9-13 in the current PDF from zilog.com agree with the above, except for IO. By default the '180 has different IO timing, but a config register can make it match the Z80)

So, I think that:
- any place where _ioread or _iowrite is used is wrong because these macros combine things that should happen in 2 different ticks. _wait should then be in a third tick.
- any place where _mwrite is used is wrong, as _mwrite combines things that should happen in 2 different ticks. The second tick should set /WR and then _wait(). It's important that the wait come after /WR because in the case of wait states, /WR should be set in the first T2, not in the last TW.
- Any place where _wait and _mread are in the same tick is wrong, the _mread has to happen in the tick before.
- opcode fetch seems to be correct, because fetch_next (M1T1) sets up for a read, then the wait happens in the next call to z80_tick (M1T2).

A fix would require moving some steps to earlier ticks. For example, I think the code above should be more like:

```
        // ED 70: IN (C) (M:2 T:8)
        // -- ioread
        case 1196: _sax(cpu0->bc,Z80_IORQ); goto step_next; // T1
        case 1197: pins |= Z80_RD; goto step_next;  // T2
        case 1198: _wait();goto step_next; // TW
        case 1199: cpu->dlatch=_gd();cpu->wz=cpu->bc+1;goto step_next; // T3
        // -- overlapped
        case 1200: _z80_in(cpu,cpu->dlatch);goto fetch_next;
```

(but probably using new macros)

**Comment by floooh** [comment]
Yes, there are some (intended) to the behaviour of a real Z80 to allow for a more efficient system tick function, see there:

https://floooh.github.io/2021/12/17/cycle-stepped-z80.html#pin-timing-differences-to-a-real-z80

Fixing the emulator to behave exactly like a real Z80 wouldn't be a big deal (just some changes to the code generator script), but then the system emulators would require a substantially more complex/expensive tick function.
