### ISSUE TITLE
Z80 XOR Malfunction

### ISSUE THREAD

**Issue by OfficialPixelBrush** [floooh/chips#77]
Basically, I'm trying to XOR A and B together.
In this case, B contains 0xF1, while A contains 0xFF.
When XORed, A gets set to 0x00.

Oddly enough, the numbers directly around this work, so setting A to 0xFE results in the expected 0x0F.
Only 0xFF in A xored with seemingly any number in any register results in the same issue.

Here's a code example to replicate my findings:
```asm
LD A,0xFF
LD B,0xF1
XOR B
```

Downloaded the latest version of the Header too.

**Comment by floooh** [comment]
hmm, that would be very strange to have slipped through ZEXALL... let me check...

**Comment by floooh** [comment]
Hmm, at least on the KC85/4 emulation it prints the correct result 0x0E:
<img width="1021" alt="Screenshot 2023-03-22 at 17 54 18" src="https://user-images.githubusercontent.com/1699414/226979910-bb12a865-bbdf-45f8-9cec-04738f75a3ed.png">

(this is basically the following program):

```
LD A,0xFF
LD B,0xF1
XOR A
```
...and then printing the A register through an operating system call.

But I think I know what the issue is, see this godbolt example:

https://www.godbolt.org/z/89TvvjE8z

You need to allow for one extra cycle after starting the CPU for the result to become ready. That's because the emulation spends one extra cycle at startup to "ignite".

E.g. when you change the line:

```c
const int num_cycles = 1 + 7 + 7 + 4;
```

...to:
```c
const int num_cycles = 1 + 7 + 7 + 4;
```

...the value in A will still be 0xFF because the XOR result isn't ready yet.

I guess that's the problem you are seeing?

**Comment by floooh** [comment]
PS: no idea why other number combinations would work though... but if there would be such an obvious bug in the emulation it would almost certainly be caught by one of the tests in the chips-test repository...

**Comment by floooh** [comment]
PPS: you're not actually running on a big endian machine do you? :D 

(because the emulation will definitely only work on little-endian because register pairs are accessed through unions)

**Comment by OfficialPixelBrush** [comment]
> Hmm, at least on the KC85/4 emulation it prints the correct result 0x0E: <img alt="Screenshot 2023-03-22 at 17 54 18" width="1021" src="https://user-images.githubusercontent.com/1699414/226979910-bb12a865-bbdf-45f8-9cec-04738f75a3ed.png">
> 
> (this is basically the following program):
> 
> ```
> LD A,0xFF
> LD B,0xF1
> XOR A
> ```
> 
> ...and then printing the A register through an operating system call.
> 
> But I think I know what the issue is, see this godbolt example:
> 
> https://www.godbolt.org/z/89TvvjE8z
> 
> You need to allow for one extra cycle after starting the CPU for the result to become ready. ~That's because the emulation spends one extra cycle at startup to "ignite"~ (what I wrote I here is just confusing - it's simply because instruction execution overlaps for one clock cycle, so the result of a sequence of instructions is only ready one clock cycle later then 'expected' - this is actually a side effect of the emulation being quite similar to a real Z80, except on a real Z80 instruction execution may overlap even more than one clock cycle).
> 
> E.g. when you change the line:
> 
> ```c
> const int num_cycles = 1 + 7 + 7 + 4;
> ```
> 
> ...to:
> 
> ```c
> const int num_cycles = 0 + 7 + 7 + 4;
> ```
> 
> ...the value in A will still be 0xFF because the XOR result isn't ready yet.
> 
> I guess that's the problem you are seeing? (hmm but I just noticed that in your case A is set to 0).
> 
> Can you post some example code which demonstrates the issue?

Here's the entire function I have thus far. It's inefficient and unfinished, I'm aware.
```asm
; Simple, Slow, Reliable
; Inputs: 
; B and C Reg
; Output: 
; B Reg, C Reg Remainder
divide:
PUSH AF; Push AF as it's only temp used here
LD A,0xFF           
; test if result will be positive or negative
XOR B           ;XOR 1111 0001 ; -15
;INC A           ;INC 0000 1110
;LD B,A          ;    0000 1111 ;  15
; check the resulting thing
LD A,B ; Load B into A for Math
LD B,0 ; Zero B to use as counter 
divideAgain:
CP C   ; Check if A-C is less than 0
JR C,divisionFinished  ; if it is, we're done
SUB C  ; otherwise A = A-C
INC B
JR divideAgain
divisionFinished: 
LD C,A
; apply signs
POP AF
RET
```

**Comment by OfficialPixelBrush** [comment]
I'm just printing the contents of cpu.a

**Comment by floooh** [comment]
> I'm just printing the contents of cpu.a

Then it's important at what cycle you read ```cpu.a```, you basically need to do this ```z80_opdone()``` returns true after the XOR instruction is executed, which is after the first cycle of the next instruction (because of the overlapped execution I talked about ealier in this thread).

**Comment by OfficialPixelBrush** [comment]
Mm, okay. Thanks for the info! I'll keep this in my mind going forward!
Also, didn't know the NEG instruction existed. That'd've saved quite a few headaches. Thank you!
