### ISSUE TITLE
m6581 - missing ringmod in Rambo Loader

### ISSUE THREAD

**Issue by realdmx** [floooh/chips#8]
Hi! I've experimented with your excellent chip implementations in my program, but there appears to be a bug in the ringmod handling. Example: Rambo Loader by Martin Galway, at 01:42-01:48 - The ringmod seems to be missing there. Hope you'll have the chance to look into it some day. Thank you!

**Comment by realdmx** [comment]
It turns out he sets waveform $43, so it's a Sync issue, not a ringmod issue. Sorry!

**Comment by realdmx** [comment]
Line 498: OLD        v->sync = (v->wav_accum & 0x00800000) &  !(prev_accum & 0x00800000);
**Line 498: NEW        v->sync = (v->wav_accum & 0x00800000) &&  !(prev_accum & 0x00800000);**
Line 562: OLD        v->wav_accum = 0;
**Line 562 NEW     v_sync->wav_accum = 0;

SYNC now triggers correctly, and should actually sync correctly, at least it sounds better :)

**Comment by floooh** [comment]
Wow, thanks :)

I'll add those fixes and update the tiny emulators page.
