### ISSUE TITLE
[zx.h] Sending space key code when Kempstone joystick is enabled.

### ISSUE THREAD

**Issue by antirez** [floooh/chips#93]
Hello Andre!

While using the Spectrum emulator I had a bug with my keymaps in games where I needed to send the space (' ') keycode.
Apparently the problem is due to the fact that the zx_key_down() function aspects 0x20 to trigger the joystick fire button:

```c
        case ZX_JOYSTICKTYPE_KEMPSTON:
            switch (key_code) {
                case 0x20:  sys->kbd_joymask |= ZX_JOYSTICK_BTN; break;
```

Hence the key never arrives to the `kbd_key_down()` code path.

If I understand correctly, those key codes mapping to joystick events exist just on the API side and not inside the Spectrum itself, so they could be replaced with key codes that are invalid characters completely, and allow emulators to send both space and joystick fire at the same time. The same is also true for the other joystick directions, but they conflict with less used keys (cursor left, right, ...), so the problem is definitely minor.

I have no problems in replacing the codes in my code, especially since I already departed significantly from the original zx.h, sadly, because of RP2040 limitations. But I wanted to ping you here about this issue.

Cheers! And thanks for your awesome work.

**Comment by floooh** [comment]
Yeah, most emulators currently suffer from this effect (that keys that trigger joystick buttons are not sent as keycodes). As far as I remember, generally enabling both inputs had problems in some emulators and games (which then would for instance receive for the joystick fire button and Space key being pressed), so disabling some key inputs when joystick mode was active was the lesser evil.

**Comment by antirez** [comment]
Thanks @floooh, I'm not sure I understood. Imagine I have a real spectrum, and press at the same time the space key and the joystick fire. The real hardware would sense both the Kempston joystick 3 bits, and the keyboard 0x20 key code. This is the behavior I'm looking for, I don't want the joystick fire to also trigger the space key press, so I guess I'm missing something.

What I did was something like that:

```diff
             break;
         case ZX_JOYSTICKTYPE_KEMPSTON:
             switch (key_code) {
-                case 0x20:  sys->kbd_joymask |= ZX_JOYSTICK_BTN; break;
-                case 0x08:  sys->kbd_joymask |= ZX_JOYSTICK_LEFT; break;
-                case 0x09:  sys->kbd_joymask |= ZX_JOYSTICK_RIGHT; break;
-                case 0x0A:  sys->kbd_joymask |= ZX_JOYSTICK_DOWN; break;
-                case 0x0B:  sys->kbd_joymask |= ZX_JOYSTICK_UP; break;
+                case 0xFF:  sys->kbd_joymask |= ZX_JOYSTICK_BTN; break;
+                case 0xFE:  sys->kbd_joymask |= ZX_JOYSTICK_LEFT; break;
+                case 0xFD:  sys->kbd_joymask |= ZX_JOYSTICK_RIGHT; break;
+                case 0xFC:  sys->kbd_joymask |= ZX_JOYSTICK_DOWN; break;
+                case 0xFB:  sys->kbd_joymask |= ZX_JOYSTICK_UP; break;
                 default:    kbd_key_down(&sys->kbd, key_code); break;
```

So a joystick event does not call kdb_key_down() of course (if that is what you thought I was proposing). It's just that API-side I have a way to trigger one or the other.

But now knowing very well the Spectrum internals I believe I may be wrong and actually the two things are related at a hardware level. Thanks.

**Comment by antirez** [comment]
Oh, I think I understand now: you mapped the joystick codes to what a vanilla Spectrum emulator sends when just passes the raw keycodes read from SDL or alike. So that if joystick is enabled, no special handling must be performed by the emulator, and people just use arrows and space. Not the best way to model that from the POV of the glue code using zx.h maybe, but it makes sense.
