### ISSUE TITLE
Wrong behavior for VIC-20 joystick

### ISSUE THREAD

**Issue by aycock** [floooh/chips#94]
Hi - thanks for the emulators! I noticed that, with the WASM VIC-20 build, when the joystick is enabled:
- space is the fire button (correct)
- right arrow moves the joystick right (correct)
- down arrow moves the joystick down (correct)
- up arrow does nothing
- left arrow registers as joystick up+left

This happens on both Chrome and Firefox under Linux, and the state as described above is reflected in the debugger UI M6522 views.

**Comment by aycock** [comment]
Thanks, much appreciated! I'm hoping to use this emulator with a university class I teach.

**Comment by floooh** [comment]
PS: keep in mind that the VIC20 emulation quality isn't all that great though. I only spend enough effort to make it basically work, but didn't put much time into compatibility tests and fixes like for the C64 and CPC.
